language: swift
osx_image: xcode10.3
xcode_sdk: iphonesimulator12.4
script:
- xcodebuild clean build test -project Ocarina.xcodeproj -scheme Ocarina -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.4'
